[ 2023-08-03 16:59:03,041 ] 27 root - INFO - Model Loaded in the ./data/model/model_y1.pkl directory successfully
[ 2023-08-03 16:59:03,041 ] 15 root - INFO - [model_loader.py] Model for Y1 is already there. So, loaded from default location
[ 2023-08-03 16:59:03,354 ] 18 root - INFO - [data_validation.py] There is no problem with the data. So, we can continue further. The data passed 'validate()'
[ 2023-08-03 16:59:03,354 ] 19 root - INFO - Data Validation is completed successfully
[ 2023-08-03 16:59:03,354 ] 18 root - INFO - [data_transformation.py] While Handling the data, there's no duplicates. The Data passed the Duplicates Handling phase
[ 2023-08-03 16:59:03,368 ] 30 root - INFO - [data_transformation.py] Got Datatypes of each column successfully
[ 2023-08-03 16:59:03,368 ] 38 root - INFO - [data_transformation.py] There is no problem with the datatype of each column. The data passed 'get_check_dtypes()' successfully.
[ 2023-08-03 16:59:03,368 ] 38 root - INFO - [model_loader.py] Somewhere the problem occurs, please check!!!
[ 2023-08-03 16:59:03,368 ] 39 root - INFO - [model_loader.py] Model is not present is the default location. So, we're going to develop a model
