[ 2023-08-03 16:08:30,642 ] 18 root - INFO - [data_validation.py] There is no problem with the data. So, we can continue further. The data passed 'validate()'
[ 2023-08-03 16:08:30,642 ] 19 root - INFO - Data Validation is completed successfully
[ 2023-08-03 16:08:30,645 ] 18 root - INFO - [data_transformation.py] While Handling the data, there's no duplicates. The Data passed the Duplicates Handling phase
[ 2023-08-03 16:08:30,646 ] 30 root - INFO - [data_transformation.py] Got Datatypes of each column successfully
[ 2023-08-03 16:08:30,646 ] 38 root - INFO - [data_transformation.py] There is no problem with the datatype of each column. The data passed 'get_check_dtypes()' successfully.
[ 2023-08-03 16:08:36,300 ] 21 root - INFO - [model_loader.py] Somewhere the problem occurs, please check!!!
[ 2023-08-03 16:08:36,307 ] 22 root - INFO - [model_loader.py] Model is not present is the default location. So, we're going to develop a model
