[ 2023-08-04 10:36:16,324 ] 18 root - INFO - [data_validation.py] There is no problem with the data. So, we can continue further. The data passed 'validate()'
[ 2023-08-04 10:36:16,324 ] 19 root - INFO - Data Validation is completed successfully
[ 2023-08-04 10:36:16,334 ] 18 root - INFO - [data_transformation.py] While Handling the data, there's no duplicates. The Data passed the Duplicates Handling phase
[ 2023-08-04 10:36:16,334 ] 30 root - INFO - [data_transformation.py] Got Datatypes of each column successfully
[ 2023-08-04 10:36:16,334 ] 38 root - INFO - [data_transformation.py] There is no problem with the datatype of each column. The data passed 'get_check_dtypes()' successfully.
